name: WebDriverIO Android CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test-android:
    name: Executar Testes Android
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Instalar dependências do projeto
        run: npm ci

      - name: Habilitar aceleração KVM (Hardware)
        run: |
          echo "🚀 Configurando aceleração para o emulador..."
          sudo chown $USER /dev/kvm

      - name: Executar testes no Emulador Android
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 34
          target: google_apis
          arch: x86_64
          profile: pixel_6
          script: npm run test:android

      # 📥 Upload dos resultados salvos para o centralizador ci-report coletar depois
      - name: Salvar Resultados do Android
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: results-android
          path: allure-results
          retention-days: 1