name: WebDriverIO Mobile CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  # JOB ANDROID
  test-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20', cache: 'npm' }
      - run: npm ci
      - run: sudo chown $USER /dev/kvm
      - uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 34
          target: google_apis
          arch: x86_64
          profile: pixel_6
          script: npm run test:android
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-results-android
          path: allure-results
          retention-days: 1

  # JOB IOS
  test-ios:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20', cache: 'npm' }
      - run: npm ci
      - name: Instalar Appium e Driver
        run: |
          # Instala a versão mais recente do appium
          npm install -g appium
          # Instala a versão mais recente do driver (o Appium 3.x precisa de drivers compatíveis)
          appium driver install xcuitest
          # Garante que o emulador inicie
          xcrun simctl boot "iPhone 15" || true
          # Executa seus testes
          npm run test:ios
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-results-ios
          path: allure-results
          retention-days: 1

  # JOB RELATÓRIO FINAL
  generate-report:
    needs: [test-android, test-ios]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: all-results
      - uses: actions/setup-java@v4
        with: { distribution: 'temurin', java-version: '17' }
      - run: |
          curl -o allure.tgz -QsL https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.29.0/allure-commandline-2.29.0.tgz
          tar -zxf allure.tgz
          sudo mv allure-2.29.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure
      - run: allure generate all-results/allure-results-android all-results/allure-results-ios --clean -o allure-report
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report
          publish_branch: gh-pages