name: Consolidated Allure Report

on:
  workflow_run:
    workflows: ["WebDriverIO Android CI", "WebDriverIO iOS CI"]
    types:
      - completed

permissions:
  contents: write

jobs:
  merge-and-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Baixar Histórico do Allure (GitHub Pages)
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: allure-history
        continue-on-error: true # Evita quebrar se for a primeiríssima execução sem gh-pages

      # 📥 Tenta baixar o artefato do Android se ele existir
      - name: Baixar Resultados do Android
        uses: actions/download-artifact@v4
        with:
          name: results-android
          path: combined-results
        continue-on-error: true

      # 📥 Tenta baixar o artefato do iOS se ele existir
      - name: Baixar Resultados do iOS
        uses: actions/download-artifact@v4
        with:
          name: results-ios
          path: combined-results
        continue-on-error: true

      - name: Gerar Allure Report Unificado
        uses: simple-elf/allure-report-action@master
        with:
          allure_results: combined-results
          allure_history: allure-history
          keep_reports: 30

      - name: Publicar no GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-history
          publish_branch: gh-pages